sudo: required
services:
  - docker

before_install:
  - docker build -t wilson/docker-r -f Dockerfile.dev .
script:
  - docker run wilson/docker-r npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: docker-r
  env: "DockerR-env"
  bucket_name: "elasticbeanstalk-us-east-1-663401331208"
  bucket_path: "docker-r"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"